config/routes.rb
Rails.application.routes.draw do
  resources :activities do
    resources :reasons
  end
  resources :appointments
  get "/reasons" => "reasons#index"
  devise_for :users
  root to: "activities#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :reasons
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
end

app/models/reason.rb
class Reason < ActiveRecord::Base
  belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end
  def menber?
    self.role == "menber"
  end
  def client?
    self.role == "client"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    @appointment = Appointment.new
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @time = Time.now
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @reasons = Reason.all
    @reasons.each do |reason|
      reason.destroy
    end
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: '活动已被成功创建。' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: '活动已被成功修改。' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @reason = @activity.reasons
    @reason.each do |reason|
        reason.destroy
    end
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: '活动已被成功删除。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :content, :date, :originator)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authenticate_admin
    unless current_user.admin?
      # flash[:alert] = "Not allow"
      redirect_to root_path
    end
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	def index
		@appointments = Appointment.all
	end

	def create
		@appointment = Appointment.new(appointment_params)
		@appointments = Appointment.all
		# 为了清除过期预约
		@appointments.each do |appointment| 
			if appointment.time.to_time - Time.now - 1.day > 0
				appointment.destroy
			end
		end
		# 重定向回主页，略显简陋
		respond_to do |format|
      		if @appointment.save
        		format.html { redirect_to activities_url, notice: '预约成功' }
      		end
    	end
	end
	
	def new
		@appointment = Appointment.new
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end
	private
		def appointment_params
      		params.require(:appointment).permit(:title, :time)
    	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
    @time = Time.now
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @activity = Activity.find(params[:activity_id])
    if @activity.reasons.find_by(name: reason_params[:name])
      respond_to do |format|
        format.html{redirect_to activities_path,notice: '你已经请假！'}
        format.html{head :no_content}
      end
    else
      @reason = @activity.reasons.create(reason_params)
      respond_to do |format|
        format.html{redirect_to activities_path,notice: '请假成功！'}
        format.html{render :show,status: :ok, location: @reason}
      end
    end
  end
  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: '请假原因已被成功修改。' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: '请假原因已被成功删除。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reason_params
      params.require(:reason).permit(:name, :why)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "个") %> 错误出现了:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui form">
    <div class="twelve wide field" style="position:relative;left:12%">
      <%= f.label :活动标题 %>
      <%= f.text_field :title %>
    </div>
    <div class="twelve wide field" style="position:relative;left:12%">
      <%= f.label :活动内容 %>
      <%= f.text_area :content, size: "10x2" %>
    </div>
  </div>
  <br>
    <div class="field" style="font-weight:700">
      <%= f.label :活动时间 %><br>
      <%#= f.datetime_select :date %>
      <%= datetime_select("activity", "date", default: 0.days.from_now) %>
    </div>
    <br>
    <div class="ui form">
      <div class="twelve wide field" style="position:relative;left:12%">
        <%= f.label :发起人 %>
        <%= f.text_field :originator %>
      </div>
      <div class="actions">
        <%= f.submit '提交活动'%>
      </div>
    </div>

<% end %>

app/views/activities/edit.html.erb
<div class="main" style = "text-align: center">
  <h1>修改活动</h1>
  <%= render 'form' %>
</div>

app/views/activities/index.html.erb
<% if current_user.client? %>
<!-- 部外人员，预约视图 -->
  <div class="main">  
    <%= form_for(@appointment) do |f| %>
      <div class="form-group">
        <label for="Appointment person">预约人</label>
        <!-- <input type="text" class="form-control" id="Appointment person" placeholder="Enter name"> -->
        <%= f.text_field :title ,class: "form-control",placeholder: "Enter name" %>
      </div>
      <div class="form-group">
        <label for="appointment time">预约时间</label><br>
        <%= date_select("appointment", "time", default: 1.days.from_now) %>
      </div><br>
      <%= f.submit %>
    <% end %>
  </div>
<% else -%>
<!-- 部内人员视图 -->
<!-- 活动表格 -->
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">活动标题</th>
          <th scope="col">活动日期</th>
          <th scope="col">发起人</th>
          <th scope="col">活动请假</th>
          <% if current_user.admin? %>
          <th scope="col">编辑活动</th>
          <th scope="col">删除活动</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @activities.each do |activity| %>
        <tr>
          <th scope="row"><%= activity.title %></td>
          <td><%= activity.date.strftime('%Y-%m-%d %H:%M') %></td>
          <td><%= activity.originator %></td>
          <td><%= link_to '活动请假', activity %></td>
          <% if current_user.admin? %>
          <td><%= link_to '编辑活动', edit_activity_path(activity) %></td>
          <td><%= link_to '删除活动', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/activities/new.html.erb
<br>

<div class="form-group" style = "text-align: center">
  <%= render 'form' %>
</div>

app/views/activities/show.html.erb
<%# if current_user.menber? and (@time - @activity.date.ago(1.day) < 0) %>
<% if (@time - @activity.date.ago(1.day) < 0) %>
  <h2> 想要请假吗? </h2>
  <%= form_for([@activity, @activity.reasons.build]) do |f| %>
  <div class="ui form" >
    <div class="twelve wide field">
      <%= f.label :姓名 %>
      <%= f.text_field :name %>
    </div>
    <div class="twelve wide field">
      <%= f.label :请假原因 %>
      <%= f.text_area :why, size: "10x5" %>
    </div>
  </div>
  <br>
  <button class="ui teal button" type="submit" style="font-size:14px;position:relative; left: 60%">
    请假
  </button>
  <% end %>
<% else %>
  <h2>不好意思，已经超过了请假期限</h2>
<% end %>

app/views/appointments/index.html.erb
<!-- 预约表格 -->
<table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">预约人</th>
          <th scope="col">预约日期</th>
        </tr>
      </thead>
      <tbody>
        <% @appointments.each do |appointment| %>
        <tr>
          <th scope="row"><%= appointment.title %></td>
          <td><%= appointment.time %></td>
        </tr>
        <% end %>
      </tbody>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>信息传媒部平台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
	<!-- # 导航栏 -->
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  	<a class="navbar-brand" href="/">主页</a>
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
  	</button>
  	<div class="collapse navbar-collapse" id="navbarColor03">
    	<ul class="navbar-nav mr-auto">
      	<% if current_user.admin? %>
      	<li class="nav-item">
        	<a class="nav-link" href="/activities/new">新建活动</a>
      	</li>
      	<li class="nav-item">
        	<a class="nav-link" href="/reasons">查看请假原因</a>
      	</li>
      	<li class="nav-item">
        	<a class="nav-link" href="/appointments">查看所有预约</a>
      	</li>
      	<% end %>
      	<li class="nav-item">
        	<a class="nav-link" href="/users/edit">修改密码</a>
      	</li>
    	</ul>
  	</div>
	</nav>
<% end %>
  <input type = "hidden" id="user" value="<%= notice %>">
  <input type = "hidden" id="log" value="<%= alert %>">
<%= yield %>
</body>
</html>

app/views/reasons/edit.html.erb
<h1>编辑请假原因</h1>

<%= render 'form' %>

<%= link_to '返回', @reason %> |
<%= link_to '返回原因列表', reasons_path %>

app/views/reasons/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">姓名</th>
      <th scope="col">请假原因</th>
      <th scope="col">活动名称</th>
      <th scope="col">查看详情</th>
    </tr>
  </thead>

  <tbody>
    <% @reasons.each do |reason| %>
    <tr>
      <th scope="row"><%= reason.name %></td>
      <td><%= reason.why %></td>
      <td><%= reason.activity.title %></td>
      <td><%= link_to '详情', activity_reason_path(reason.activity,reason) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/reasons/show.html.erb
<div class="main">
  <div class="grid" style="font-size:17px">
  <div class="sixteen wide column">

    <strong>姓名:</strong>
    <%= @reason.name %>
  </div>
  <div class="sixteen wide column">
    <strong>请假原因:</strong>
    <%= @reason.why %>
  </div>
  <div class="sixteen wide column">
    <strong>活动名称:</strong>
    <%= @reason.activity.title %>
  </div>
  </div>
</div>

<div class="bottom">
  <%= link_to '返回', reasons_path %>
</div>